name: Metrics Renders
on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:

      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: picture/base.png
          token: ${{ secrets.METRICS_TOKEN }}
          user: CompPsyUnion
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai

      - name: Mostused
        uses: lowlighter/metrics@latest
        with:
          filename: picture/mostused.png
          token: ${{ secrets.METRICS_TOKEN }}
          user: CompPsyUnion
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
      - name: People
        uses: lowlighter/metrics@latest
        with:
          filename: picture/people.png
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: members

      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          filename: picture/activity.png
          token: ${{ secrets.METRICS_TOKEN }}
          user: CompPsyUnion
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: picture/facts.png
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Shanghai

      - name: Opened
        uses: lowlighter/metrics@latest
        with:
          filename: picture/followup.png
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_archived: yes
