name: Update Members Wall

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * 1' # 每周一触发

jobs:
  update-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Create update_members.js
        run: |
          echo "const fetch = require('node-fetch');" > update_members.js
          echo "const fs = require('fs');" >> update_members.js
          echo "" >> update_members.js
          echo "async function fetchTeams() {" >> update_members.js
          echo "  const response = await fetch('https://api.github.com/orgs/CompPsyUnion/teams', {" >> update_members.js
          echo "    headers: {" >> update_members.js
          echo "      'Authorization': \`token \${process.env.PAT_TOKEN}\`," >> update_members.js
          echo "      'Accept': 'application/vnd.github.v3+json'," >> update_members.js
          echo "    }," >> update_members.js
          echo "  });" >> update_members.js
          echo "  return await response.json();" >> update_members.js
          echo "}" >> update_members.js
          echo "" >> update_members.js
          echo "async function fetchMembers() {" >> update_members.js
          echo "  const response = await fetch('https://api.github.com/orgs/CompPsyUnion/members', {" >> update_members.js
          echo "    headers: {" >> update_members.js
          echo "      'Authorization': \`token \${process.env.PAT_TOKEN}\`," >> update_members.js
          echo "      'Accept': 'application/vnd.github.v3+json'," >> update_members.js
          echo "    }," >> update_members.js
          echo "  });" >> update_members.js
          echo "  return await response.json();" >> update_members.js
          echo "}" >> update_members.js
          echo "" >> update_members.js
          echo "async function fetchUserTeams(login) {" >> update_members.js
          echo "  const response = await fetch(\`https://api.github.com/orgs/CompPsyUnion/members/\${login}/teams\`, {" >> update_members.js
          echo "    headers: {" >> update_members.js
          echo "      'Authorization': \`token \${process.env.PAT_TOKEN}\`," >> update_members.js
          echo "      'Accept': 'application/vnd.github.v3+json'," >> update_members.js
          echo "    }," >> update_members.js
          echo "  });" >> update_members.js
          echo "  return await response.json();" >> update_members.js
          echo "}" >> update_members.js
          echo "" >> update_members.js
          echo "async function main() {" >> update_members.js
          echo "  const teams = await fetchTeams();" >> update_members.js
          echo "  const members = await fetchMembers();" >> update_members.js
          echo "" >> update_members.js
          echo "  const teamMembers = {};" >> update_members.js
          echo "  for (const team of teams) {" >> update_members.js
          echo "    teamMembers[team.name] = [];" >> update_members.js
          echo "  }" >> update_members.js
          echo "" >> update_members.js
          echo "  for (const member of members) {" >> update_members.js
          echo "    const login = member.login;" >> update_members.js
          echo "    const avatar_url = member.avatar_url;" >> update_members.js
          echo "    const userTeams = await fetchUserTeams(login);" >> update_members.js
          echo "" >> update_members.js
          echo "    userTeams.forEach(team => {" >> update_members.js
          echo "      const teamName = team.name;" >> update_members.js
          echo "      teamMembers[teamName].push(\`\${login}|<img height='48' width='48' src='\${avatar_url}'>\`);" >> update_members.js
          echo "    });" >> update_members.js
          echo "  }" >> update_members.js
          echo "" >> update_members.js
          echo "  let content = '# Organization Members\\n';" >> update_members.js
          echo "" >> update_members.js
          echo "  for (const team in teamMembers) {" >> update_members.js
          echo "    content += \`## \${team}\\n\`;" >> update_members.js
          echo "    content += '|:construction_worker:|:construction_worker:|:construction_worker:|:construction_worker:|:construction_worker:|:construction_worker:|\\n';" >> update_members.js
          echo "    content += '|:-------------------:|:-------------------:|:-------------------:|:-------------------:|:-------------------:|:-------------------:|\\n';" >> update_members.js
          echo "" >> update_members.js
          echo "    const membersRow = teamMembers[team];" >> update_members.js
          echo "    while (membersRow.length > 0) {" >> update_members.js
          echo "      const row = membersRow.splice(0, 6).join('|');" >> update_members.js
          echo "      content += row + '\\n';" >> update_members.js
          echo "    }" >> update_members.js
          echo "  }" >> update_members.js
          echo "" >> update_members.js
          echo "  fs.writeFileSync('members.md', content);" >> update_members.js
          echo "}" >> update_members.js
          echo "" >> update_members.js
          echo "main().catch(err => {" >> update_members.js
          echo "  console.error(err);" >> update_members.js
          echo "  process.exit(1);" >> update_members.js
          echo "});" >> update_members.js

      - name: Run update_members.js
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: node update_members.js

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add members.md
          git commit -m "Update members wall"
          git push
