name: Update Members Wall

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-members:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install node-fetch@latest

      - name: Update members
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          node update_members.js

      - name: Replace members section in README
        run: |
          members_content=$(cat members.md)
          perl -i -0777 -pe 's/<!--START_SECTION:members-->.*<!--END_SECTION:members-->/<!--START_SECTION:members--> \n'"$members_content"'\n<!--END_SECTION:members-->/s' README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update members wall in README"
          git push
