name: Update Members Wall

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * 1' # 每周一触发

jobs:
  update-members:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm install node-fetch@latest

      - name: Update members
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          node update_members.js

      - name: Replace members section in README
        run: |
          # 读取 README.md 和 members.md 文件内容
          readme_content=$(cat README.md)
          members_content=$(cat members.md)

          # 使用 awk 替换特定的部分
          echo "$readme_content" | awk -v new_content="$members_content" '
            BEGIN { found=0 }
            /<!--START_SECTION:members-->/ { print; found=1; next }
            /<!--END_SECTION:members-->/ { print new_content; found=0 }
            !found { print }
          ' > README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update members wall in README"
          git push
